package contact.directory.view.form;

import contact.directory.controller.NeighborhoodController;
import contact.directory.enums.ValidationMessage;
import contact.directory.model.Neighborhood;
import contact.directory.model.Commune;
import contact.directory.view.model.BarrioTableModel;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author C.Mateo
 */
public class NeighborhoodForm extends javax.swing.JPanel {

    private Commune comuna;
    private BarrioTableModel tablaBarrios;
    private NeighborhoodController barrioController;

    /**
     * Creates new form BarrioForm
     */
    public NeighborhoodForm() {
        initComponents();
        init();
    }

    private void init() {
        tablaBarrios = new BarrioTableModel();
        jTableBarrios.setModel(tablaBarrios);
    }

    public void setActionListener(ActionListener actionListener){
        eliminarButton.addActionListener(actionListener);
    }
    
    public JTextField getNombreTxt() {
        return nombreTxt;
    }

    public Commune getComuna() {
        return comuna;
    }
    
    public Neighborhood getBarrio() {
        String nombre = getNombreTxt().getText();
        return new Neighborhood(-1, nombre, getComuna());
    }

    public void setComuna(Commune comuna) {
        this.comuna = comuna;
        setComunaNameLb(comuna.getName());
        barrioController.getNeighborhoodByCommune(comuna);
    }

    public void setComunaNameLb(String name) {
        ComunaNameLb.setText(name);
    }

    public void setBarrioController(NeighborhoodController barrioController) {
        this.barrioController = barrioController;
    }

    public void cargarBarrios(List<Neighborhood> barrios) {
        SwingUtilities.invokeLater(() -> {
            tablaBarrios.setListaBarrios(barrios);
        });
    }
    
    public void limpiarCampos(){
        nombreTxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBarrios = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ComunaNameLb = new javax.swing.JLabel();
        buscarTxt = new javax.swing.JTextField();
        eliminarButton = new javax.swing.JButton();
        nombreTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTableBarrios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nombre"
            }
        ));
        jScrollPane1.setViewportView(jTableBarrios);

        jLabel1.setText("Comuna Cargada: ");

        ComunaNameLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        buscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarTxtKeyReleased(evt);
            }
        });

        eliminarButton.setText("Guardar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-20.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buscarTxt)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(nombreTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComunaNameLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(ComunaNameLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarButton))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void buscarTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTxtKeyReleased
        // TODO add your handling code here:

        Thread thread = new Thread() {

            @Override
            public void run() {
                String response;
                String key = buscarTxt.getText();

                if (!key.isEmpty()) {
                    response = barrioController.searchNeighborhoodByCommune(comuna, key);
                } else {
                    response = barrioController.getNeighborhoodByCommune(comuna);
                }

                if (!response.equals(ValidationMessage.OPERACION_EXITOSA.getMessage())) {
                    javax.swing.JOptionPane.showMessageDialog(null, response);
                }

            }
        };

        thread.start();
    }//GEN-LAST:event_buscarTxtKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int index = jTableBarrios.getSelectedRow();
        Neighborhood barrio = tablaBarrios.getListaBarrios().get(index);
        String response = barrioController.deleteNeighborhood(barrio);
        javax.swing.JOptionPane.showMessageDialog(null, response);
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComunaNameLb;
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBarrios;
    private javax.swing.JTextField nombreTxt;
    // End of variables declaration//GEN-END:variables

}
