package contact.directory.view.form;

import contact.directory.controller.PersonController;
import contact.directory.enums.ValidationMessage;
import contact.directory.model.Neighborhood;
import contact.directory.model.City;
import contact.directory.model.Commune;
import contact.directory.model.Address;
import contact.directory.model.Person;
import java.awt.event.ActionEvent;
import java.util.List;

/**
 *
 * @author C.Mateo
 */
public class PersonForm extends javax.swing.JPanel {

    private PersonController votanteController;

    /**
     * Creates new form VontanteForm
     */
    public PersonForm() {
        initComponents();
    }

    public void setVotanteController(PersonController votanteController) {
        this.votanteController = votanteController;
        init();
    }

    private void init() {
        ciudadComboBox.getComboBox().addActionListener((ActionEvent e) -> {
            City ciudadSeleccionada = (City) ciudadComboBox.getComboBox().getSelectedItem();
            if (ciudadSeleccionada != null) {
                votanteController.onCitySelected(ciudadSeleccionada);
            }
        });

        comunaComboBox.getComboBox().addActionListener((ActionEvent e) -> {
            Commune comunaSeleccionada = (Commune) comunaComboBox.getComboBox().getSelectedItem();
            if (comunaSeleccionada != null) {
                votanteController.onCommuneSelected(comunaSeleccionada);
            }
        });
    }

    public void cargarCiudades(List<City> ciudades) {
        ciudadComboBox.loadItems(ciudades);
    }

    public void cargarComunas(List<Commune> comunas) {
        comunaComboBox.loadItems(comunas);
    }

    public void cargarBarrios(List<Neighborhood> barrios) {
        barrioComboBox.loadItems(barrios);
    }

    public void limpiarCampos() {
        primerNombreTxt.setText("");
        segundoNombreTxt.setText("");
        primerApellidoTxt.setText("");
        segundoApellidoTxt.setText("");
        cedulaTxt.setText("");
        telefonoTxt.setText("");
        calleTxt.setText("");
        carreraTxt.setText("");
        numeroTxt.setText("");
        sobreTxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        primerNombreTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        segundoNombreTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        primerApellidoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundoApellidoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        calleTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        carreraTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        numeroTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        sobreTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cedulaTxt = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        ciudadComboBox = new contact.directory.view.components.CiudadComboBox();
        comunaComboBox = new contact.directory.view.components.ComunaComboBox();
        barrioComboBox = new contact.directory.view.components.BarrioComboBox();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Primer Nombre:");

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Segundo Nombre:");

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Primer Apellido:");

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Segundo Apellido:");

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Calle:");

        calleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calleTxtActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Carrera:");

        carreraTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraTxtActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Número:");

        numeroTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroTxtActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Sobre:");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Cédula:");

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Teléfono:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Observación:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(440, 440, 440)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ciudadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(comunaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(barrioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primerApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(segundoApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primerNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(segundoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carreraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(sobreTxt))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primerNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoNombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primerApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segundoApellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cedulaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefonoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ciudadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comunaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barrioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carreraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void carreraTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carreraTxtActionPerformed

    private void numeroTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String primerNombre = primerNombreTxt.getText();
        String segundoNombre = segundoNombreTxt.getText();
        String primerApellido = primerApellidoTxt.getText();
        String segundoApellido = segundoApellidoTxt.getText();
        String cedula = cedulaTxt.getText();
        String telefono = telefonoTxt.getText();

        Neighborhood barrio = (Neighborhood) barrioComboBox.getComboBox().getSelectedItem();
        String calle = calleTxt.getText();
        String carrera = carreraTxt.getText();
        String numero = numeroTxt.getText();
        String sobre = sobreTxt.getText();

        Address direccion = new Address(-1, calle, carrera, numero, sobre, barrio);

        Person persona = new Person(
                -1,
                cedula,
                primerNombre,
                segundoNombre,
                primerApellido,
                segundoApellido,
                telefono,
                direccion);

        String response = votanteController.savePerson(persona);
        
        if (response.equals(ValidationMessage.VOTANTE_GUARDADO.getMessage())) {
            limpiarCampos();
        }

        javax.swing.JOptionPane.showMessageDialog(null, response);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void calleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calleTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private contact.directory.view.components.BarrioComboBox barrioComboBox;
    private javax.swing.JTextField calleTxt;
    private javax.swing.JTextField carreraTxt;
    private javax.swing.JTextField cedulaTxt;
    private contact.directory.view.components.CiudadComboBox ciudadComboBox;
    private contact.directory.view.components.ComunaComboBox comunaComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JTextField primerApellidoTxt;
    private javax.swing.JTextField primerNombreTxt;
    private javax.swing.JTextField segundoApellidoTxt;
    private javax.swing.JTextField segundoNombreTxt;
    private javax.swing.JTextField sobreTxt;
    private javax.swing.JTextField telefonoTxt;
    // End of variables declaration//GEN-END:variables

}
