package com.software.elector.view.components;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author C.Mateo
 */
public class ComboBox<T> extends javax.swing.JPanel {
    
    private final DefaultComboBoxModel<T> comboBoxModel = new DefaultComboBoxModel<>();
    
    /**
     * Creates new form CiudadForm
     */
    public ComboBox() {
        initComponents();
        init();
    }
    
    private void init(){
        ComboBox.setModel(comboBoxModel);
    }
    
    public void setTitle(String title){
        titleLb.setText(title);
    }
    
    public JComboBox getComboBox(){
        return ComboBox;
    }
    
    public void loadItems(List<T> items){
        comboBoxModel.removeAllElements();
        for(T t: items){
            comboBoxModel.addElement(t);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBox = new javax.swing.JComboBox<>();
        titleLb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        titleLb.setForeground(new java.awt.Color(51, 51, 51));
        titleLb.setText("Title:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLb)
                    .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLb)
                .addGap(3, 3, 3)
                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<T> ComboBox;
    private javax.swing.JLabel titleLb;
    // End of variables declaration//GEN-END:variables
}
