package com.software.elector.view;

import com.software.elector.controller.VotanteController;
import com.software.elector.model.Persona;
import com.software.elector.view.form.VotanteForm;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author C.Mateo
 */
public class VotantePanel extends javax.swing.JPanel {

    private VotanteForm votanteForm;
    private VotanteController votanteController;
    private final DefaultTableModel tablaVotantes;
    

    /**
     * Creates new form VotantePanel
     */
    public VotantePanel() {
        initComponents();
        tablaVotantes = (DefaultTableModel) jTableVotantes.getModel();
    }
    
    public void setVotanteController(VotanteController votanteController) {
        this.votanteController = votanteController;
    }
    
    
    public void setVotanteForm(VotanteForm votanteForm){
        this.votanteForm = votanteForm;
    }

    public void cargarVontantes(List<Persona> personas) {
        tablaVotantes.setRowCount(0);
        for (Persona persona : personas) {
            tablaVotantes.addRow(new String[]{
                String.format(
                "%s %s",
                persona.getPrimerNombre(),
                persona.getSegundoNombre()
                ),
                String.format(
                "%s %s",
                persona.getPrimerApellido(),
                persona.getSegundoApellido()
                ),
                persona.getCedula(),
                persona.getTelefono(),
                String.format(
                        "Calle %s Carrera %s Nro %s Sobre %s", 
                        persona.getDireccion().getCalle(),
                        persona.getDireccion().getCarrera(),
                        persona.getDireccion().getNumero(),
                        persona.getDireccion().getSobre()
                ),
                persona.getDireccion().getBarrio().getNombre(),
                persona.getDireccion().getBarrio().getComuna().getNombre(),
                persona.getDireccion().getBarrio().getComuna().getCiudad().getNombre()
                }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVotantes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        buscarTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Cedula", "Telefono", "Direccion", "Barrio", "Comuna", "Ciudad"
            }
        ));
        jScrollPane1.setViewportView(jTableVotantes);

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarTxtKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-20.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MainDialog(votanteForm, "Registro Nuevo Votante");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTxtKeyReleased
        // TODO add your handling code here:
        String key = buscarTxt.getText();
        if(!key.isEmpty()){
            votanteController.buscarPorClave(key);
        } else {
            votanteController.cargarVotantes();
        }
    }//GEN-LAST:event_buscarTxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVotantes;
    // End of variables declaration//GEN-END:variables
}
