package contact.directory.view;

import contact.directory.controller.PersonController;
import contact.directory.enums.ValidationMessage;
import contact.directory.model.Person;
import contact.directory.view.form.PersonForm;
import contact.directory.view.model.PersonaTableModel;
import java.util.List;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.SwingUtilities;

/**
 *
 * @author C.Mateo
 */
public class PersonPanel extends javax.swing.JPanel {

    private PersonForm votanteForm;
    private PersonController votanteController;
    private PersonaTableModel tablaVotantes;

    /**
     * Creates new form VotantePanel
     */
    public PersonPanel() {
        initComponents();
        init();
    }

    private void init() {
        tablaVotantes = new PersonaTableModel();
        jTableVotantes.setModel(tablaVotantes);
    }

    public void setVotanteController(PersonController votanteController) {
        this.votanteController = votanteController;
    }

    public void setVotanteForm(PersonForm votanteForm) {
        this.votanteForm = votanteForm;
    }

    public void cargarVontantes(List<Person> personas) {
        SwingUtilities.invokeLater(() -> {
            tablaVotantes.setListaPersonas(personas);
            totalRegistrosLb.setText(
                    String.format("%d Registros ", personas.size())
            );
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVotantes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        buscarTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        totalRegistrosLb = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Cedula", "Telefono", "Direccion", "Barrio", "Comuna", "Ciudad"
            }
        ));
        jTableVotantes.setRowHeight(30);
        jScrollPane1.setViewportView(jTableVotantes);

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buscarTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarTxtKeyReleased(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-20.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        totalRegistrosLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalRegistrosLb.setText("0 Registros");

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 442, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalRegistrosLb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(buscarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRegistrosLb)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new MainDialog(votanteForm, "Registro Nuevo Votante");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buscarTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarTxtKeyReleased
        // TODO add your handling code here:

        Thread thread = new Thread() {

            @Override
            public void run() {

                String mensaje;
                String key = buscarTxt.getText();

                if (!key.isEmpty()) {
                    mensaje = votanteController.searchPeople(key);
                } else {
                    mensaje = votanteController.loadPeopleAndUpdateView();
                }

                if (!mensaje.equals(ValidationMessage.OPERACION_EXITOSA.getMessage())) {
                    javax.swing.JOptionPane.showMessageDialog(null, mensaje);
                }
            }

        };

        thread.start();

    }//GEN-LAST:event_buscarTxtKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int selectedRow = jTableVotantes.getSelectedRow();
        if (selectedRow >= 0) {
            Person persona = tablaVotantes.getListaPersonas().get(selectedRow);
            int selectedOption = javax.swing.JOptionPane.showConfirmDialog(null, 
                    String.format("¿Desea eliminar la persona de nombre %s %s?", persona.getFirstName(), persona.getLastName()),
                    "Seleccione una opción",
                    YES_NO_OPTION,
                    WARNING_MESSAGE
            );
            //Implementación para eliminar un registro
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscarTxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVotantes;
    private javax.swing.JLabel totalRegistrosLb;
    // End of variables declaration//GEN-END:variables
}
