package contact.directory.view;

import contact.directory.view.interfaces.ActionListenerRegistration;
import contact.directory.model.Person;
import contact.directory.view.components.JTextFieldKeyReleased;
import contact.directory.view.form.PersonForm;
import contact.directory.view.interfaces.KeyReleasedListener;
import contact.directory.view.model.PersonaTableModel;
import java.awt.event.ActionListener;
import java.util.List;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.SwingUtilities;
import contact.directory.view.interfaces.PersonView;

/**
 *
 * @author C.Mateo
 */
public class PersonPanel extends javax.swing.JPanel implements PersonView, ActionListenerRegistration {

    private PersonForm personForm;
    private PersonaTableModel tablaVotantes;

    /**
     * Creates new form VotantePanel
     */
    public PersonPanel() {
        initComponents();
        init();
    }

    private void init() {
        tablaVotantes = new PersonaTableModel();
        jTableVotantes.setModel(tablaVotantes);
    }

    public void setPersonForm(PersonForm personForm) {
        this.personForm = personForm;
    }

    @Override
    public void loadPeopleInView(List<Person> people) {
        SwingUtilities.invokeLater(() -> {
            tablaVotantes.setListaPersonas(people);
            updateTotalPeopleLabel(people.size());
        });
    }

    private void updateTotalPeopleLabel(int size) {
        String text = String.format("%d Registros ", size);
        totalRegistrosLb.setText(text);
    }

    @Override
    public Person getPersonToDelete() {
        return null;
    }

    @Override
    public void addActionListener(ActionListener actionListener) {
        deletePersonBtn.addActionListener(actionListener);
    }

    public void addKeyStrokeListener(KeyReleasedListener keyReleasedListener) {
        searchPeopleTxt.setKeyReleasedListener(keyReleasedListener);
    }

    public JTextFieldKeyReleased getSearchPeopleTxt() {
        return searchPeopleTxt;
    }

    @Override
    public String getSearchTextPerson() {
        return searchPeopleTxt.getText();
    }

    @Override
    public Person getPersonData() {
        Person person;
        int selectedRow = jTableVotantes.getSelectedRow();
        if (selectedRow >= 0) {
            person = tablaVotantes.getListaPersonas().get(selectedRow);

            int selectedOption = javax.swing.JOptionPane.showConfirmDialog(null,
                    String.format("¿Desea eliminar la persona de nombre %s %s?", person.getFirstName(), person.getLastName()),
                    "Seleccione una opción",
                    YES_NO_OPTION,
                    WARNING_MESSAGE
            );

            if (selectedOption == javax.swing.JOptionPane.YES_OPTION) {
                return person;
            }

        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVotantes = new javax.swing.JTable();
        addPersonBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalRegistrosLb = new javax.swing.JLabel();
        deletePersonBtn = new javax.swing.JButton();
        searchPeopleTxt = new contact.directory.view.components.JTextFieldKeyReleased();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableVotantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Cedula", "Telefono", "Direccion", "Barrio", "Comuna", "Ciudad"
            }
        ));
        jTableVotantes.setRowHeight(30);
        jScrollPane1.setViewportView(jTableVotantes);

        addPersonBtn.setText("Nuevo");
        addPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-20.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        totalRegistrosLb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalRegistrosLb.setText("0 Registros");

        deletePersonBtn.setText("Eliminar");
        deletePersonBtn.setActionCommand("view1_delete");

        searchPeopleTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPeopleTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchPeopleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 438, Short.MAX_VALUE)
                        .addComponent(deletePersonBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addPersonBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(totalRegistrosLb, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addPersonBtn)
                        .addComponent(deletePersonBtn))
                    .addComponent(jLabel2)
                    .addComponent(searchPeopleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalRegistrosLb)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonBtnActionPerformed
        // TODO add your handling code here:
        new MainDialog(personForm, "Registro Nuevo Votante");
    }//GEN-LAST:event_addPersonBtnActionPerformed

    private void searchPeopleTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPeopleTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchPeopleTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonBtn;
    private javax.swing.JButton deletePersonBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVotantes;
    private contact.directory.view.components.JTextFieldKeyReleased searchPeopleTxt;
    private javax.swing.JLabel totalRegistrosLb;
    // End of variables declaration//GEN-END:variables

}
